# First, add a virtual HDD for w1.rst.com.
#
# Create a playbook to create a partition & mount it.

---

- name: "Play1"
  hosts: w1.rst.com
  remote_user: auser
  become: yes
  become_method: sudo
  tasks:
          - name: "Create Disk Partition"
            parted:
                    device: /dev/sda
                    label: msdos
                    number: 1
                    part_type: primary
                    part_start: 0GB
                    part_end: 10GB
                    unit: GB
                    state: present
          - name: "create mount point"
            file:
                    name: /abcd
                    state: directory
          - name: "format the partition"
            filesystem:
                         dev: /dev/sda1
                         fstype: xfs
                         force: yes
          - name: "mount the partition"
            mount:
                    src: /dev/sda1
                    path: /abcd
                    fstype: xfs
                    state: mounted
