# First, add a new ethenet card on w1.rst.com
#
# Create a playbook to configure IPv4 addr (20.0.0.200/24),
# gateway (200.0.250) on the newly added network card. 

---

- name: "Play1"
  hosts: w1.rst.com
  remote_user: auser
  become: true
  become_method: sudo
  tasks:
          - name: " configure IP addr to the interface"
            nmcli:
                    conn_name: eth1
                    type: ethernet
                    ifname: eth1
                    ip4: 20.0.0.200/24
                    gw4: 20.0.0.250
                    state: present
                    autoconnect: yes

          - name: "restart NetworkManager"
            service: 
                      name: NetworkManager
                      state: restarted
          
          - name: "Verify IP address configured"
            command:
                      ifconfig
            register: OP
          - debug: 
                   msg: The IP address is "{{ OP.stdout }}"
