# Create a playbook based on condition defined or not:
# In this case, a condition is defined ( when: filename is defined)
# so since the variable is not defined above this a false statement
# & it will not perform the copy task.


---

- name: "Play1: Copy the file when it meets the comparison"
  hosts: "w2.rst.com"
  remote_user: "auser"
  become: yes
  become_method: sudo
  vars:


  tasks:
          - name: "task1: copy the file when matched"
            copy:
                   src: "{{ filename }}"
                   dest: /usr/local/bin
            when:
                   filename is defined

